# Generated by Django 4.2 on 2023-04-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pillarnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('eastings', models.FloatField()),
                ('northings', models.FloatField()),
            ],
            options={
                'db_table': 'coordinate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plannumber', models.CharField(db_column='PlanNumber', max_length=50, primary_key=True, serialize=False)),
                ('area', models.FloatField(blank=True, db_column='Area', null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('surveyor', models.CharField(blank=True, db_column='Surveyor', max_length=255, null=True)),
                ('coordinatesystem', models.CharField(blank=True, db_column='CoordinateSystem', max_length=255, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
    ]
